

# Basic
name:               "Glaser Lab"
title:              "title"
description:        "description"

# URL
url:                https://glaserlab.github.io
production_url:     https://glaserlab.github.io/
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html



# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
#   - name:           "about"
#     href:           "/about"
  - name:           "research"
    href:           "/research"
  - name:           "people"
    href:           "/people"
  - name:           "publications"
    href:           "/publication"
  - name:           "code"
    href:           "/code"
  - name:           "join us"
    href:           "/contact"
#   - name:           "cv"
#     href:           "/JG_CV_1221_Web.pdf"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
